spring:

  datasource:
    url: jdbc:mysql://database-21.c8ucrampvv9z.ap-south-1.rds.amazonaws.com:3306/emsdb
    username: admin
    password: 12345678 
 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect